In [3]:
from sklearn.metrics.pairwise import paired_euclidean_distances
from sklearn.metrics.pairwise import paired_manhattan_distances
from sklearn.metrics.pairwise import paired_cosine_distances

x=[[1,2,3,4,5]]
y=[[2,3,4,5,6]]

In [9]:
paired_euclidean_distances(x,y) # compute euclidean distance

array([ 2.23606798])

In [7]:
paired_manhattan_distances(x,y) # compute manhatta distance

array([ 5.])

In [8]:
paired_cosine_distances(x,y) # compute cosine distance

array([ 0.00506332])

In [11]:
#聚类不需要y 它自动给分类
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[1,2],[1,4],[1,0],[4,2],[4,4],[4,0]])
kmeans = KMeans(n_clusters=2,random_state=0).fit(X)
kmeans.labels_

array([0, 0, 0, 1, 1, 1])

In [26]:
from sklearn import datasets
from sklearn.metrics import accuracy_score
iris = datasets.load_iris()
X = iris.data
kmeans = KMeans(n_clusters=3,random_state=0).fit(X)

labels = []
for y in kmeans.labels_:
    if (y == 1):
        labels.append(0)
    elif (y == 0):
        labels.append(1)
    else:
        labels.append(y)
accuracy_score(iris.target, labels) 

0.89333333333333331

In [18]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [19]:
print(kmeans.labels_)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 2
 2 0]
